export function DINotFoundException(message: string) {
   return new Error(message)
}
